name = "englishvidya"
compatibility_date = "2026-06-03"

# Eleventy build output folder
pages_build_output_dir = "./_site"

[assets]
directory = "./_site"

# --- Cloudflare D1 Database ---
[[d1_databases]]
binding = "DB"
database_name = "englishvidya-db"
database_id = "9421954b-e317-42a7-97bf-d47fc5721807"
